### PR TITLE
Fixed it was two different names on seedID

### PR DESCRIPTION
**Pull request by Stekeblad**
Fixed that it sometimes was "seedID" and sometimes only "ID"
Now its "seedID" on all seeds

Just a little change making it looking the same way in the entire file. I think seedID is a better name then just ID.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Thanks!

**Comment by Stekeblad** [comment]
A few questions about this file:  How are the seeds loaded into the game? I'm almost finished with my automation program then I discovered the file here don't have the seeds listed in the same order as my game.  It seems like the mod has not been updated since any large change was made in the seed file.

If  for example you don't have Ender IO, will the mod while loading the seeds skip the seeds depending on enderIO AND their ID or will it affect the ids of seeds later in the file?
for example
1: iron
2: vibrant
3: enderium
no enderIO so no vibrant,  will enderium have ID 2 or 3?

How about instead of depending on mods checking if the item produced/required is listed in oreDict? There are many mods using tin and copper, but the seeds only appear if ThermalFoundation is loaded.

Are any updates on the way? This little thing breaks my program :D it thinks bronze is silver...
If not, I can help add some more seeds and then call it "All the Seeds Update" or something :)

**Comment by jaredlll08** [comment]
Well I plan on updating to 1.8.9, at which point I'll maybe rewrite it fully.
Take a look at SeedRegistry. I'll be honest, I have no idea how stuff like that is handled, You would need to ask @JHarb52207

**Comment by ghost** [comment]
It has been way to long for me to remember exactly how this thing works.  From what I can recall, if the file isn't there at start the mod makes a default one based on a master file we provided.  The file is loaded only at start, any changes to the file from that point on are ignored until the mod restarts.  The mod also wipes and re-writes the file from its in memory array about every 5 min.

All seeds in the file should be loaded into the in memory array even if their mod is missing.  When the mod attempts to add the item(s) and receipie(s) for the seed it checks for dependent mods and skips it if needed.

For ID generation it starts at 1 and goes until it finds an int that isn't in the in memory array, so if your just looking at seeds that are items you could overwrite something in the array.

**Pull request merged**
